export default [
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('2bac4151c28d40c9977fc67648ca94d5')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "2bac4151c28d40c9977fc67648ca94d5",
        "endDate": "2021-05-16",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-05-16",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('083d45f858de4d409ff1f30d827f5025')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "083d45f858de4d409ff1f30d827f5025",
        "endDate": "2021-05-22",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-05-22",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('c401e0a2f00840b09191df924f7b7130')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "c401e0a2f00840b09191df924f7b7130",
        "endDate": "2021-05-23",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-05-23",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('63f51c692c5947d885c63559b5806f2c')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "63f51c692c5947d885c63559b5806f2c",
        "endDate": "2021-05-30",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-05-30",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('712645ec7c4b42a2ba6f828ce131df9c')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "712645ec7c4b42a2ba6f828ce131df9c",
        "endDate": "2021-06-05",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-05",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('05ddbdf5a9db45c09a460b4690d8512a')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "05ddbdf5a9db45c09a460b4690d8512a",
        "endDate": "2021-06-06",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-06",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('DragonBoatFestival_1623427200000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "DragonBoatFestival_1623427200000",
        "endDate": "2021-06-12",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "端午节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-12",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('fecc3ecca0b746c799ece63a0857ed6a')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "fecc3ecca0b746c799ece63a0857ed6a",
        "endDate": "2021-06-12",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-12",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('DragonBoatFestival_1623513600000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "DragonBoatFestival_1623513600000",
        "endDate": "2021-06-13",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "端午节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-13",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('8a6b5e44a0fb47d494d255c6504a461b')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "8a6b5e44a0fb47d494d255c6504a461b",
        "endDate": "2021-06-13",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-13",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('DragonBoatFestival_1623600000000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "DragonBoatFestival_1623600000000",
        "endDate": "2021-06-14",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "端午节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-14",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('244152350b59477f8cac4edb8048a8b5')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "244152350b59477f8cac4edb8048a8b5",
        "endDate": "2021-06-14",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-14",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('502c4d0ea1e04b17bf29b19ebe324fbb')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "502c4d0ea1e04b17bf29b19ebe324fbb",
        "endDate": "2021-06-20",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-20",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('4e48c38117054c93af4b2b804f3b7a6e')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "4e48c38117054c93af4b2b804f3b7a6e",
        "endDate": "2021-06-26",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-26",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('3130083dfb4746fea270a31f11c105d1')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "3130083dfb4746fea270a31f11c105d1",
        "endDate": "2021-06-27",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-06-27",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('50765a309010449196ca47449ff48718')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "50765a309010449196ca47449ff48718",
        "endDate": "2021-07-04",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-07-04",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('b682b63f18bb477681f0d36c85117dcf')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "b682b63f18bb477681f0d36c85117dcf",
        "endDate": "2021-07-10",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-07-10",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('696071c2e4314a35a9cc069df51623f4')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "696071c2e4314a35a9cc069df51623f4",
        "endDate": "2021-07-11",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-07-11",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('2715f84f64424b389dbda0c5332144ac')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "2715f84f64424b389dbda0c5332144ac",
        "endDate": "2021-07-18",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-07-18",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('784d11c206424652a534e85db16d97cb')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "784d11c206424652a534e85db16d97cb",
        "endDate": "2021-07-24",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-07-24",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('884664f1036a4b36bd0724a59acca738')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "884664f1036a4b36bd0724a59acca738",
        "endDate": "2021-07-25",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-07-25",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('ac1fd180f8ef40d48da49b17650e981b')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "ac1fd180f8ef40d48da49b17650e981b",
        "endDate": "2021-08-01",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-01",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('c7f5eb0de4074620b2df12e850db1ece')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "c7f5eb0de4074620b2df12e850db1ece",
        "endDate": "2021-08-07",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-07",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('805ab1fb8a5d4749b2680d8e67ca75ac')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "805ab1fb8a5d4749b2680d8e67ca75ac",
        "endDate": "2021-08-08",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-08",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('9732c3a18be7453187d6999891d0e679')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "9732c3a18be7453187d6999891d0e679",
        "endDate": "2021-08-15",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-15",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('efd6a67e092e4ee7923cf1f5b87ae70a')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "efd6a67e092e4ee7923cf1f5b87ae70a",
        "endDate": "2021-08-21",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-21",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('1b885b01eb23451eab01554ecdf2ad99')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "1b885b01eb23451eab01554ecdf2ad99",
        "endDate": "2021-08-22",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-22",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('a443e7c20e6c4ad5b727d87c9953c9ab')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "a443e7c20e6c4ad5b727d87c9953c9ab",
        "endDate": "2021-08-29",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-08-29",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },

    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('a0ba395f7c6c465a9b98bdb831948098')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "a0ba395f7c6c465a9b98bdb831948098",
        "endDate": "2021-09-04",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-04",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('5656e2b765414879a4019a774c42face')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "5656e2b765414879a4019a774c42face",
        "endDate": "2021-09-05",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-05",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('8e9341bfa6404f2ead65e95250a0c4ae')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "8e9341bfa6404f2ead65e95250a0c4ae",
        "endDate": "2021-09-12",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-12",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('mid-autumnfestival_1631980800000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "mid-autumnfestival_1631980800000",
        "endDate": "2021-09-19",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "中秋节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-19",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('9f331ab36cd7461486abdcac1a183785')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "9f331ab36cd7461486abdcac1a183785",
        "endDate": "2021-09-19",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-19",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('mid-autumnfestival_1632067200000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "mid-autumnfestival_1632067200000",
        "endDate": "2021-09-20",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "中秋节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-20",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('1772e48844e549c9a4f71722bf5546c5')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "1772e48844e549c9a4f71722bf5546c5",
        "endDate": "2021-09-20",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-20",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('mid-autumnfestival_1632153600000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "mid-autumnfestival_1632153600000",
        "endDate": "2021-09-21",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "中秋节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-21",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('5f16b43e4d3e4b69b15d331cac8e832b')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "5f16b43e4d3e4b69b15d331cac8e832b",
        "endDate": "2021-09-21",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-09-21",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633017600000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633017600000",
        "endDate": "2021-10-01",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-01",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('715e4cc83d894b49ac027b2d6bcef054')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "715e4cc83d894b49ac027b2d6bcef054",
        "endDate": "2021-10-01",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-01",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633104000000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633104000000",
        "endDate": "2021-10-02",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-02",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('1c297ace336b440e965caf9fd543aea6')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "1c297ace336b440e965caf9fd543aea6",
        "endDate": "2021-10-02",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-02",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633190400000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633190400000",
        "endDate": "2021-10-03",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-03",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('e996e0d060f34e7db5ad4718ecb323bb')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "e996e0d060f34e7db5ad4718ecb323bb",
        "endDate": "2021-10-03",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-03",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633276800000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633276800000",
        "endDate": "2021-10-04",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-04",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('9eb65a68f9db430fa6290ce68e6d9fb1')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "9eb65a68f9db430fa6290ce68e6d9fb1",
        "endDate": "2021-10-04",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-04",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633363200000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633363200000",
        "endDate": "2021-10-05",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-05",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('f022de4259d74dfdabcbf49f9db6266d')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "f022de4259d74dfdabcbf49f9db6266d",
        "endDate": "2021-10-05",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-05",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633449600000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633449600000",
        "endDate": "2021-10-06",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-06",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('5e68a3b8192b4739851fb9d648a366aa')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "5e68a3b8192b4739851fb9d648a366aa",
        "endDate": "2021-10-06",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-06",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('NationalDay_1633536000000')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "NationalDay_1633536000000",
        "endDate": "2021-10-07",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "HOLIDAY",
        "duration": "1",
        "translatedStatus": "节假日",
        "isEditable": false,
        "externalName": "国庆节",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-07",
        "status": "Holiday",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('df4dfc4fa0c2422cb270870eecbaf9ba')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "df4dfc4fa0c2422cb270870eecbaf9ba",
        "endDate": "2021-10-07",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-07",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('8ba18ef418d14b419522e180f8bfa085')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "8ba18ef418d14b419522e180f8bfa085",
        "endDate": "2021-10-10",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-10",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('d572986c752b4d80b9a3186244c4aa2b')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "d572986c752b4d80b9a3186244c4aa2b",
        "endDate": "2021-10-17",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-17",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('7ace090f7a0c4a55be36a187f1ed3f0c')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "7ace090f7a0c4a55be36a187f1ed3f0c",
        "endDate": "2021-10-23",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-23",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('4f6c6c54c53045579e0cc20728b634c1')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "4f6c6c54c53045579e0cc20728b634c1",
        "endDate": "2021-10-24",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-24",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('6f5140a1c7174df98f82fbdf7d6e0540')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "6f5140a1c7174df98f82fbdf7d6e0540",
        "endDate": "2021-10-31",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-10-31",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },

    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('658a1b1d1514491d804d1ea5eb460e1b')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "658a1b1d1514491d804d1ea5eb460e1b",
        "endDate": "2021-11-06",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-11-06",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('824222a7165c45a897a3d6d716530377')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "824222a7165c45a897a3d6d716530377",
        "endDate": "2021-11-07",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-11-07",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('8125c176a04c45479666b080e4aeb3ea')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "8125c176a04c45479666b080e4aeb3ea",
        "endDate": "2021-11-14",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-11-14",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('351fcc788cf9449eadfc77eb9276fd84')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "351fcc788cf9449eadfc77eb9276fd84",
        "endDate": "2021-11-20",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-11-20",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('cdfe69a15d534217ba46b904fb979059')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "cdfe69a15d534217ba46b904fb979059",
        "endDate": "2021-11-21",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-11-21",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('1b0c5dbab70c4bde871f55a930fb28f7')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "1b0c5dbab70c4bde871f55a930fb28f7",
        "endDate": "2021-11-28",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-11-28",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('2c333071205a4c7791dc71ec0fd79a5c')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "2c333071205a4c7791dc71ec0fd79a5c",
        "endDate": "2021-12-04",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-12-04",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('f8ac213f87dc460189e71ed49dc9c56e')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "f8ac213f87dc460189e71ed49dc9c56e",
        "endDate": "2021-12-05",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-12-05",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('a77a4813ffcf4fb383c654d4fd7d8f94')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "a77a4813ffcf4fb383c654d4fd7d8f94",
        "endDate": "2021-12-12",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-12-12",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('60841ef423f94472a4981a40822d1d12')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "60841ef423f94472a4981a40822d1d12",
        "endDate": "2021-12-18",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-12-18",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('d679e710b9ba4963a4f87a9e9f99c1d1')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "d679e710b9ba4963a4f87a9e9f99c1d1",
        "endDate": "2021-12-19",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-12-19",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    },
    {
        "__metadata": {
            "uri": "https://performancemanager15.sapsf.cn/odata/v2/restricted/TimeTypeBalance,UpcomingAbsences,TimeAccountBalanceOverview,EmployeeTime,AbsenceWorkflowInfo,TeamAbsenceCalendar/UpcomingAbsences('e4c7111d1cef420bbc24a82b2051ea7b')",
            "type": "SFOData.UpcomingAbsences"
        },
        "externalCode": "e4c7111d1cef420bbc24a82b2051ea7b",
        "endDate": "2021-12-26",
        "translatedTimeUnit": "天",
        "hasWorkflow": false,
        "workflowRequestId": null,
        "type": "NON_WORKING_DAY",
        "duration": "1",
        "translatedStatus": "已批准",
        "isEditable": false,
        "externalName": "Non Working Day",
        "isEnabledInEssScenario": true,
        "timeInterval": null,
        "startDate": "2021-12-26",
        "status": "APPROVED",
        "timeUnit": "DAYS"
    }
]